name: checkin

on:
  schedule:
    - cron: '00 04 * * *'
    # 每天中午12点签到

  workflow_dispatch: # click the button on Github repo!

env:
  email: ${{ secrets.EMAIL }}
  passwd: ${{ secrets.TOKEN }}
  code: ''
  mainURL: 'https://www.cordcloud.one'
  bakURL: 'https://www.c-cloud.xyz'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - run: yarn
      - run: yarn start
